/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.rngouveia.customer

import spock.lang.Ignore
import spock.lang.Specification

@Ignore
class ApplicationTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new Application()

        when:
        def result = app.greeting

        then:
        result != null
    }
}
